name: Publish to NuGet

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: '8.0.x'

    - name: Create new project
      run: dotnet new console --name RobloxCS

    - name: Package the project
      run: dotnet pack --configuration Release

    - name: Publish the package
      run: dotnet nuget push "bin/Release/RobloxCS.1.0.0.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"