name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add GitHub source to NuGet
      run: dotnet nuget add source --name github "https://nuget.pkg.github.com/roblox-csharp/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build (Release)
      run: dotnet build -c Release --no-restore
    - name: Build (Debug)
      run: dotnet build -c Debug --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
